print('100 + 50')
print("hola" + " " + 'Fede')
print("Me llamo \"Federico\"")
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print('Este signo \\ es una barra invertida')